### ISSUE TITLE
Add a default response for /info

### ISSUE THREAD

**Issue by InfinityPlus05** [JuhJuhButts/Vagan#6]
At the moment, it only gives info on specific people. I feel like if a name doesn't have info listed, it should just default to
`an asshole`
instead of just saying nothing.

**Comment by JuhJuhButts** [comment]
probably not that response but yeah i'll add a default to info

**Comment by InfinityPlus05** [comment]
#

> probably not that response but yeah i'll add a default to info

what about "a human bean"

**Comment by JuhJuhButts** [comment]
Getting fixed in its slash command counterpart.
